import torch
data = torch.tensor([30,])
print(data)
print(type(data))
print(data.size(0))
item = data.item()
print(item)
print('='*50)
data = torch.tensor(30)
print(data)
print(type(data))
print(data.size())
item = data.item()
print(item)
print('='*50)
data = torch.tensor([[30,50],[50,60],[10,90]])
print(data)
print(data.shape)
print(data.size(0))
print(data.size(1))
